### ISSUE TITLE
Possible Virus

### ISSUE THREAD

**Issue by RA5TAMAN** [bp2008/HikPasswordHelper#1]
![image](https://user-images.githubusercontent.com/40676119/42062093-70f46058-7afa-11e8-81c2-704fbe47b8a7.png)
Norton caught something backdoor

**Comment by bp2008** [comment]
Looks like a classic case of false-alarming.

**Comment by RA5TAMAN** [comment]
quite possible, this program saved me tho, clients cams were hacked and password changed. Thanks
